CRS_PRESENT = "crs.present"
CRS_WKT = "crs.wkt"
CRS_AUTHORITY = "crs.authority"
CRS_CODE = "crs.code"
CRS_KIND = "crs.kind"
CRS_AXIS_UNITS = "crs.axis_units"
CRS_AREA_OF_USE_BOUNDS = "crs.area_of_use.bounds"
CRS_AREA_OF_USE_NAME = "crs.area_of_use.name"

SPATIAL_BOUNDS = "spatial.bounds"

VECTOR_GEOMETRY_COUNT = "vector.geometry.count"
VECTOR_INVALID_GEOMETRY_COUNT = "vector.geometry.invalid_count"
VECTOR_EMPTY_GEOMETRY_COUNT = "vector.geometry.empty_count"
VECTOR_GEOMETRY_TYPES = "vector.geometry.types"

RASTER_WIDTH = "raster.width"
RASTER_HEIGHT = "raster.height"
RASTER_RESOLUTION = "raster.resolution"
RASTER_TRANSFORM = "raster.transform"
RASTER_BAND_COUNT = "raster.band_count"
RASTER_DTYPES = "raster.dtypes"
RASTER_NODATA = "raster.nodata"
RASTER_NODATA_COLLISION_BANDS = "raster.nodata_collision_bands"

RELATION_BOUNDS_OVERLAP = "relation.bounds.overlap"
RELATION_OVERLAP_RATIO = "relation.bounds.overlap_ratio"
RELATION_GRID_ALIGNED = "relation.grid.aligned"
RELATION_GRID_OFFSET_PIXELS = "relation.grid.offset_pixels"
